services:
  ai-devs-rag-pgvector:
    image: pgvector/pgvector:pg17
    container_name: ai-devs-rag-pgvector
    environment:
      POSTGRES_USER: mateusz
      POSTGRES_PASSWORD: adam
      POSTGRES_DB: jakub
    ports:
      - "5433:5432"
    volumes:
      - ai-devs-rag-pgvector-data:/var/lib/postgresql/data

volumes:
  ai-devs-rag-pgvector-data:
